"use client";

import { FormEvent, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type Contact = { id:string; workspace_id:string; company_id:string|null; name:string; email:string|null; phone:string|null; role_title:string|null; contact_type:string|null };
type Company = { id:string; name:string };
type Note = { id:string; body:string; created_at:string };
type FollowUp = { id:string; title:string; due_date:string|null; priority:number; status:string };

export function ContactOperations({ contact, companies, initialNotes, initialFollowUps }: { contact:Contact; companies:Company[]; initialNotes:Note[]; initialFollowUps:FollowUp[] }) {
  const [record,setRecord]=useState(contact); const [notes,setNotes]=useState(initialNotes); const [followUps,setFollowUps]=useState(initialFollowUps);
  const [name,setName]=useState(contact.name); const [email,setEmail]=useState(contact.email??""); const [phone,setPhone]=useState(contact.phone??""); const [role,setRole]=useState(contact.role_title??""); const [company,setCompany]=useState(contact.company_id??""); const [type,setType]=useState(contact.contact_type??"external");
  const [note,setNote]=useState(""); const [title,setTitle]=useState(""); const [due,setDue]=useState(""); const [priority,setPriority]=useState(2); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function run(action:()=>Promise<void>){setBusy(true);setMessage("");try{await action();}catch(error){setMessage(error instanceof Error?error.message:"The operation could not be completed.");}finally{setBusy(false);}}
  function save(event:FormEvent){event.preventDefault();run(async()=>{const {data,error}=await (getSupabaseBrowserClient() as any).rpc("kos_update_contact",{target_workspace:contact.workspace_id,target_contact:contact.id,contact_name:name,contact_email:email,contact_phone:phone,contact_role:role,target_company:company||null,contact_type_value:type});if(error)throw error;setRecord(data);setMessage("Contact updated and audited.");});}
  function addNote(event:FormEvent){event.preventDefault();if(!note.trim())return;run(async()=>{const {data,error}=await (getSupabaseBrowserClient() as any).rpc("kos_add_contact_note",{target_workspace:contact.workspace_id,target_contact:contact.id,note_body:note});if(error)throw error;setNotes(items=>[data,...items]);setNote("");setMessage("Note added to the governed contact record.");});}
  function createFollowUp(event:FormEvent){event.preventDefault();if(!title.trim())return;run(async()=>{const {data,error}=await (getSupabaseBrowserClient() as any).rpc("kos_create_follow_up",{target_workspace:contact.workspace_id,target_contact:contact.id,follow_up_title:title,follow_up_due:due||null,follow_up_priority:priority});if(error)throw error;setFollowUps(items=>[data,...items]);setTitle("");setDue("");setMessage("Follow-up created and audited.");});}
  return <section className="contact-operations">{message&&<p className="app-notice" role="status">{message}</p>}<div className="operations-grid"><form onSubmit={save}><p className="eyebrow">Edit contact</p><h2>Core details</h2><label>Name<input value={name} onChange={e=>setName(e.target.value)} required /></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)} /></label><label>Role<input value={role} onChange={e=>setRole(e.target.value)} /></label><label>Company<select value={company} onChange={e=>setCompany(e.target.value)}><option value="">Not assigned</option>{companies.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Relationship type<select value={type} onChange={e=>setType(e.target.value)}><option value="external">External</option><option value="employee">Employee</option><option value="consultant">Consultant</option><option value="owner">Owner</option><option value="director">Director</option><option value="legal">Legal adviser</option><option value="tax_advisor">Tax adviser</option></select></label><button disabled={busy}>Save audited changes</button><small>Current saved record: {record.name}</small></form><div><form onSubmit={addNote}><p className="eyebrow">Contact memory</p><h2>Add note</h2><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Meeting context, preference, or important relationship detail" /><button disabled={busy||!note.trim()}>Add governed note</button></form><div className="operations-list">{notes.map(item=><article key={item.id}><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString()}</small></article>)}{!notes.length&&<p>No notes recorded yet.</p>}</div></div><div><form onSubmit={createFollowUp}><p className="eyebrow">Next action</p><h2>Create follow-up</h2><label>Action<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Call about annual filing" /></label><label>Due date<input type="date" value={due} onChange={e=>setDue(e.target.value)} /></label><label>Priority<select value={priority} onChange={e=>setPriority(Number(e.target.value))}><option value={1}>High</option><option value={2}>Normal</option><option value={3}>Low</option></select></label><button disabled={busy||!title.trim()}>Create audited follow-up</button></form><div className="operations-list">{followUps.map(item=><article key={item.id}><strong>{item.title}</strong><span>{item.status} · priority {item.priority}{item.due_date?` · due ${item.due_date}`:""}</span></article>)}{!followUps.length&&<p>No follow-up is open.</p>}</div></div></div></section>;
}
