import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";
const migration=await readFile(new URL("../../supabase/migrations/20260813214942_second_brain_governance_and_retrieval.sql",import.meta.url),"utf8");const hardening=await readFile(new URL("../../supabase/migrations/20260813215502_harden_knowledge_governance_privileges.sql",import.meta.url),"utf8");const page=await readFile(new URL("../../app/workspace/knowledge/page.tsx",import.meta.url),"utf8");
const resolution=await readFile(new URL("../../supabase/migrations/20260813233638_resolve_knowledge_contradictions.sql",import.meta.url),"utf8");const actions=await readFile(new URL("../../app/workspace/knowledge/actions.ts",import.meta.url),"utf8");
const retrieval=await readFile(new URL("../../supabase/migrations/20260813234452_harden_knowledge_retrieval_policy.sql",import.meta.url),"utf8");
test("knowledge relations enforce workspace integrity and append-only supersession",()=>{assert.match(migration,/foreign key \(source_knowledge_id,workspace_id\)/);assert.match(migration,/foreign key \(target_knowledge_id,workspace_id\)/);assert.match(migration,/verification_status='superseded'/);assert.match(migration,/Replacement created as candidate/)});
test("knowledge governance denies anonymous RPCs and direct mutation",()=>{assert.match(hardening,/revoke all on table public\.kos_knowledge_relations from anon,authenticated/);assert.match(hardening,/grant select on table public\.kos_knowledge_relations to authenticated/);for(const name of ["kos_search_knowledge","kos_record_knowledge_relation","kos_supersede_knowledge"])assert.match(hardening,new RegExp(`revoke all on function public\\.${name}`))});
test("knowledge review exposes retrieval contradiction and supersession controls",()=>{for(const label of ["Search knowledge","Record governed relationship","Create superseding revision","Contradiction and supersession ledger"])assert.match(page,new RegExp(label))});
test("open contradictions have an owner-admin resolution workflow with evidence and audit",()=>{for(const label of ["Resolve contradiction","Resolution reason and evidence","Resolve and audit"])assert.match(page,new RegExp(label));assert.match(actions,/kos_resolve_knowledge_relation/);assert.match(resolution,/only open contradictions can be resolved/);assert.match(resolution,/knowledge_contradiction_resolved/);assert.match(resolution,/kos_has_role\(target_workspace,array\['owner','admin'/);assert.match(resolution,/from public,anon/)});
test("retrieval is permission-first, grant-aware, citation-bearing and freshness ranked",()=>{assert.match(retrieval,/kos_can_read_knowledge/);assert.match(retrieval,/resource_type='knowledge'/);assert.match(retrieval,/g\.user_id=\(select auth\.uid\(\)\)/);assert.match(retrieval,/record_visibility='workspace' and record_sensitivity <> 'restricted'/);assert.doesNotMatch(retrieval,/from public\.kos_knowledge_items k\s+where k\.id=target_knowledge/);assert.match(retrieval,/drop function if exists public\.kos_search_knowledge/);assert.match(retrieval,/verification_status when 'verified'/);assert.match(retrieval,/now\(\)-k\.updated_at/);assert.match(retrieval,/jsonb_agg\(jsonb_build_object\('source_type'/);for(const label of ["Freshness","View citations","unsupported until evidence is linked"])assert.match(page,new RegExp(label))});
