create unique index if not exists kos_projects_workspace_identity on public.kos_projects(workspace_id,id);
create table public.kos_commitments (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.kos_workspaces(id) on delete cascade,
 company_id uuid, asset_id uuid, project_id uuid references public.kos_projects(id) on delete set null,
 commitment_type text not null, title text not null, description text, status text not null default 'planned', priority text not null default 'normal',
 starts_at timestamptz, ends_at timestamptz, due_at timestamptz, location text, travel_details jsonb not null default '{}'::jsonb,
 assigned_to uuid references auth.users(id), created_by uuid not null default auth.uid() references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(workspace_id,company_id) references public.kos_companies(workspace_id,id), foreign key(workspace_id,asset_id) references public.kos_assets(workspace_id,id), foreign key(workspace_id,project_id) references public.kos_projects(workspace_id,id),
 check(commitment_type in('task','calendar_event','travel','deadline','approval_follow_up')), check(status in('planned','active','waiting','done','cancelled')), check(priority in('low','normal','high','urgent')), check(ends_at is null or starts_at is null or ends_at>=starts_at)
);
create index kos_commitments_timeline on public.kos_commitments(workspace_id,coalesce(starts_at,due_at),status);
alter table public.kos_commitments enable row level security;
create policy kos_commitments_read on public.kos_commitments for select to authenticated using(public.kos_is_member(workspace_id) and (asset_id is null or exists(select 1 from public.kos_assets a where a.id=asset_id and a.workspace_id=kos_commitments.workspace_id and (a.visibility='workspace' or a.created_by=(select auth.uid()) or public.kos_has_role(a.workspace_id,array['owner','admin']::public.kos_workspace_role[])))));
create policy kos_commitments_insert on public.kos_commitments for insert to authenticated with check(public.kos_has_role(workspace_id,array['owner','admin','member']::public.kos_workspace_role[]) and created_by=(select auth.uid()) and (company_id is null or exists(select 1 from public.kos_companies c where c.id=company_id and c.workspace_id=kos_commitments.workspace_id)) and (asset_id is null or exists(select 1 from public.kos_assets a where a.id=asset_id and a.workspace_id=kos_commitments.workspace_id and (a.visibility='workspace' or a.created_by=(select auth.uid()) or public.kos_has_role(a.workspace_id,array['owner','admin']::public.kos_workspace_role[])))));
create policy kos_commitments_update on public.kos_commitments for update to authenticated using(public.kos_has_role(workspace_id,array['owner','admin','member']::public.kos_workspace_role[]) and (asset_id is null or exists(select 1 from public.kos_assets a where a.id=asset_id and a.workspace_id=kos_commitments.workspace_id and (a.visibility='workspace' or a.created_by=(select auth.uid()) or public.kos_has_role(a.workspace_id,array['owner','admin']::public.kos_workspace_role[]))))) with check(public.kos_has_role(workspace_id,array['owner','admin','member']::public.kos_workspace_role[]) and (asset_id is null or exists(select 1 from public.kos_assets a where a.id=asset_id and a.workspace_id=kos_commitments.workspace_id and (a.visibility='workspace' or a.created_by=(select auth.uid()) or public.kos_has_role(a.workspace_id,array['owner','admin']::public.kos_workspace_role[])))));
create policy kos_commitments_delete on public.kos_commitments for delete to authenticated using(created_by=(select auth.uid()) or public.kos_has_role(workspace_id,array['owner','admin']::public.kos_workspace_role[]));
grant select,insert,update,delete on public.kos_commitments to authenticated;
