create table public.kos_extraction_reviews (
 id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.kos_workspaces(id) on delete cascade,document_id uuid not null,document_version_id uuid not null,representation_id uuid,
 field_path text not null,predicted_value jsonb not null,confidence numeric not null check(confidence between 0 and 1),risk_class text not null check(risk_class in('standard','legal','financial','identity','restricted')),threshold numeric not null check(threshold between 0 and 1),status text not null default 'pending' check(status in('pending','approved','corrected','rejected')),corrected_value jsonb,reason text,extractor text not null,extractor_version text not null,reviewed_by uuid references auth.users(id),created_at timestamptz not null default now(),reviewed_at timestamptz,
 unique(document_version_id,field_path,extractor_version),foreign key(workspace_id,document_id) references public.kos_documents(workspace_id,id) on delete cascade,foreign key(workspace_id,document_version_id) references public.kos_document_versions(workspace_id,id) on delete cascade,foreign key(workspace_id,representation_id) references public.kos_document_representations(workspace_id,id) on delete cascade
);
create index kos_extraction_reviews_queue on public.kos_extraction_reviews(workspace_id,status,risk_class,confidence);
alter table public.kos_extraction_reviews enable row level security;
create policy kos_extraction_reviews_read on public.kos_extraction_reviews for select to authenticated using(public.kos_is_member(workspace_id));
revoke all on public.kos_extraction_reviews from public,anon,authenticated;grant select on public.kos_extraction_reviews to authenticated;
create or replace function public.kos_record_extraction_review(target_workspace uuid,target_document uuid,target_version uuid,target_representation uuid,field_value text,prediction jsonb,confidence_value numeric,risk_value text,extractor_value text,extractor_version_value text) returns public.kos_extraction_reviews language plpgsql security invoker set search_path='' as $$
declare threshold_value numeric;review public.kos_extraction_reviews;begin if not public.kos_has_role(target_workspace,array['owner','admin','member']::public.kos_workspace_role[]) then raise exception 'write membership required' using errcode='42501';end if;if risk_value not in('standard','legal','financial','identity','restricted') then raise exception 'invalid risk class' using errcode='22023';end if;threshold_value:=case risk_value when 'standard' then .80 when 'identity' then .92 else 1.00 end;insert into public.kos_extraction_reviews(workspace_id,document_id,document_version_id,representation_id,field_path,predicted_value,confidence,risk_class,threshold,extractor,extractor_version) values(target_workspace,target_document,target_version,target_representation,field_value,prediction,confidence_value,risk_value,threshold_value,extractor_value,extractor_version_value) on conflict(document_version_id,field_path,extractor_version) do update set predicted_value=excluded.predicted_value,confidence=excluded.confidence,risk_class=excluded.risk_class,threshold=excluded.threshold,status='pending',corrected_value=null,reason=null,reviewed_by=null,reviewed_at=null returning * into review;return review;end $$;
create or replace function public.kos_resolve_extraction_review(target_workspace uuid,target_review uuid,decision_value text,correction_value jsonb,reason_value text) returns public.kos_extraction_reviews language plpgsql security invoker set search_path='' as $$
declare review public.kos_extraction_reviews;begin if not public.kos_has_role(target_workspace,array['owner','admin']::public.kos_workspace_role[]) then raise exception 'owner or admin required' using errcode='42501';end if;if decision_value not in('approved','corrected','rejected') then raise exception 'invalid review decision' using errcode='22023';end if;if coalesce(trim(reason_value),'')='' then raise exception 'review reason required' using errcode='22023';end if;select * into review from public.kos_extraction_reviews where id=target_review and workspace_id=target_workspace and status='pending' for update;if review.id is null then raise exception 'pending review not found in workspace' using errcode='P0002';end if;if decision_value='corrected' and correction_value is null then raise exception 'correction value required' using errcode='22023';end if;update public.kos_extraction_reviews set status=decision_value,corrected_value=case when decision_value='corrected' then correction_value else null end,reason=reason_value,reviewed_by=(select auth.uid()),reviewed_at=now() where id=review.id returning * into review;insert into public.kos_audit_events(workspace_id,actor_user_id,action,resource_type,resource_id,details) values(target_workspace,(select auth.uid()),'extraction_review_resolved','extraction_review',review.id,jsonb_build_object('decision',decision_value,'risk_class',review.risk_class,'field_path',review.field_path,'reason',reason_value));return review;end $$;
revoke all on function public.kos_record_extraction_review(uuid,uuid,uuid,uuid,text,jsonb,numeric,text,text,text) from public,anon;revoke all on function public.kos_resolve_extraction_review(uuid,uuid,text,jsonb,text) from public,anon;grant execute on function public.kos_record_extraction_review(uuid,uuid,uuid,uuid,text,jsonb,numeric,text,text,text) to authenticated;grant execute on function public.kos_resolve_extraction_review(uuid,uuid,text,jsonb,text) to authenticated;
